AWSTemplateFormatVersion: 2010-09-09
Description: >-
  S3 Template: S3 Bucket and Bucket Policy 

# This template creates:
#   S3 Bucket
#   S3 Bucket Policy

Parameters:

  BucketName:
    Description: Your S3 Bucket name
    Type: String

  S3EndpointId:
    Description: The S3 Endpoint ID of VPC
    Type: String

######################
# Resources section
######################

Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Suspended 
      # CorsConfiguration: 
      #   CorsRules: 
      #   - AllowedHeaders: 
      #       - '*'
      #   - AllowedMethods: 
      #       - GET
      #   - AllowedOrigins: 
      #       - '*'
      #   - MaxAge: 3000
        

  S3BucketPolicyViaEndpoint:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub '${S3Bucket.Arn}/*'
            Principal: "*"
            Condition:
              StringEquals:
                # 'aws:sourceVpce': {'Fn::ImportValue': !Sub '${NetworkStackName}-S3EndpointGWID'}  
                aws:sourceVpce': !Ref S3EndpointId

  S3BucketPolicyPublic:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub '${S3Bucket.Arn}/*'

######################
# Outputs section
######################

Outputs:
  
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'